# Generated by Django 6.1 on 2026-08-31 00:39

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_profile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='certificates/'),
        ),
    ]
